"""Shared data models for the module engine."""

from datetime import datetime
from enum import Enum
from uuid import UUID, uuid4

from pydantic import BaseModel, Field


class Severity(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class ArtifactType(str, Enum):
    IP = "ip"
    DOMAIN = "domain"
    URL = "url"
    HASH = "hash"
    EMAIL = "email"
    USER_ID = "user_id"
    CARD_BIN = "card_bin"
    FINGERPRINT = "fingerprint"
    SESSION_ID = "session_id"
    API_KEY = "api_key"


class Artifact(BaseModel):
    """An Indicator of Compromise (IOC) or forensic artifact."""
    type: ArtifactType
    value: str
    context: str | None = None


class AlertModel(BaseModel):
    """Alert generated by a detection module."""
    id: UUID = Field(default_factory=uuid4)
    tenant_id: str
    source: str
    event_type: str
    severity: Severity
    confidence: float = Field(ge=0.0, le=1.0)
    title: str
    description: str | None = None
    raw_payload: dict | None = None
    artifacts: list[Artifact] = []
    mitre_technique: str | None = None
    atlas_technique: str | None = None
    trace_id: str | None = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


class StreamEvent(BaseModel):
    """Deserialized event from a Redis Stream."""
    entry_id: str
    tenant_id: str
    source: str
    event_type: str
    severity_hint: str
    timestamp: str
    raw_payload: dict
    trace_id: str = ""
    metadata: dict = {}
